name: Retag Docker Image
description: Retag a Docker image in Casavo CR using buildx imagetools
author: Casavo
inputs:
  image:
    description: Docker image name (e.g. org/image)
    required: true
  source-tag:
    description: Source tag of the Docker image to retag
    required: false
    default: ${{ github.sha }}
  target-tag:
    description: New tag to assign to the Docker image
    required: false
    default: production
  registry-hostname:
    description: Docker registry hostname
    required: false
    default: cr.production.casavo.tech
  registry-username:
    description: Docker registry username
    required: false
  registry-password:
    description: Docker registry password
    required: false
  

runs:
  using: composite
  steps:
    - uses: docker/setup-buildx-action@v3

    - name: Login to Casavo CR
      if: ${{ inputs.registry-username && inputs.registry-password }}
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry-hostname }}
        username: ${{ inputs.registry-username }}
        password: ${{ inputs.registry-password }}

    - name: Retag image
      run: |
        docker buildx imagetools create --tag ${{ inputs.registry-hostname }}/${{ inputs.image }}:${{ inputs.target-tag }} ${{ inputs.registry-hostname }}/${{ inputs.image }}:${{ inputs.source-tag }}
      shell: bash
